import type { Project, DataSource, Template, PageSection, User, AnalyticsSummary } from './types';

export const DEFAULT_PALETTES = [
  ['#1e3a5f', '#c9a962', '#4a90a4', '#7cb342', '#ff8a65', '#5c6bc0'],
  ['#0d7377', '#14ffec', '#323232', '#0d7377', '#21d4fd', '#b721ff'],
  ['#2d3436', '#e17055', '#00b894', '#0984e3', '#6c5ce7', '#fdcb6e'],
  ['#1a1a2e', '#e94560', '#16213e', '#0f3460', '#533483', '#f5c518'],
];

export const MOCK_USER: User = {
  id: 'u-001',
  name: '张明远',
  email: 'zhangmy@company.com',
  role: 'admin',
  createdAt: '2024-01-15T09:00:00Z',
};

export const MOCK_COLLABORATORS: Omit<User, 'createdAt'>[] = [
  { id: 'u-002', name: '李雪婷', email: 'lixt@company.com', role: 'data_manager' },
  { id: 'u-003', name: '王浩然', email: 'wanghr@company.com', role: 'editor' },
  { id: 'u-004', name: '陈思敏', email: 'chensm@company.com', role: 'editor' },
  { id: 'u-005', name: '刘建国', email: 'liujg@company.com', role: 'viewer' },
];

export const MOCK_TEMPLATES: Template[] = [
  {
    id: 'tpl-corporate-blue',
    name: '商务深蓝',
    category: '经典商务',
    theme: {
      primaryColor: '#1e3a5f',
      secondaryColor: '#2c5282',
      accentColor: '#c9a962',
      backgroundColor: '#ffffff',
      textColor: '#1a202c',
      headingFont: 'Cormorant Garamond',
      bodyFont: 'Manrope',
      borderRadius: 'md',
      shadowIntensity: 'medium',
    },
    isCustom: false,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'tpl-emerald-tech',
    name: '翡翠科技',
    category: '科技感',
    theme: {
      primaryColor: '#0d7377',
      secondaryColor: '#14ffec',
      accentColor: '#21d4fd',
      backgroundColor: '#0a0a0a',
      textColor: '#e0e0e0',
      headingFont: 'Space Grotesk',
      bodyFont: 'Manrope',
      borderRadius: 'lg',
      shadowIntensity: 'strong',
    },
    isCustom: false,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'tpl-warm-elegance',
    name: '暖调典雅',
    category: '简约优雅',
    theme: {
      primaryColor: '#2d3436',
      secondaryColor: '#636e72',
      accentColor: '#e17055',
      backgroundColor: '#faf8f5',
      textColor: '#2d3436',
      headingFont: 'Playfair Display',
      bodyFont: 'Inter',
      borderRadius: 'sm',
      shadowIntensity: 'light',
    },
    isCustom: false,
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: 'tpl-modern-mono',
    name: '现代极简',
    category: '极简风格',
    theme: {
      primaryColor: '#000000',
      secondaryColor: '#333333',
      accentColor: '#f5c518',
      backgroundColor: '#ffffff',
      textColor: '#111111',
      headingFont: 'DM Serif Display',
      bodyFont: 'Helvetica Neue',
      borderRadius: 'none' as any,
      shadowIntensity: 'none',
    },
    isCustom: false,
    createdAt: '2024-01-01T00:00:00Z',
  },
];

export const MOCK_REVENUE_DATA: Record<string, any>[] = [
  { quarter: 'Q1 2023', revenue: 8500, profit: 1280, users: 125000 },
  { quarter: 'Q2 2023', revenue: 9800, profit: 1560, users: 148000 },
  { quarter: 'Q3 2023', revenue: 11200, profit: 1890, users: 176000 },
  { quarter: 'Q4 2023', revenue: 14500, profit: 2680, users: 212000 },
  { quarter: 'Q1 2024', revenue: 12800, profit: 2180, users: 245000 },
  { quarter: 'Q2 2024', revenue: 15600, profit: 2890, users: 289000 },
  { quarter: 'Q3 2024', revenue: 18200, profit: 3520, users: 342000 },
  { quarter: 'Q4 2024', revenue: 22800, profit: 4780, users: 418000 },
];

export const MOCK_CITY_DATA: Record<string, any>[] = [
  { city: '北京', users: 68500, revenue: 4820, growth: 23.5 },
  { city: '上海', users: 72800, revenue: 5180, growth: 21.2 },
  { city: '深圳', users: 54200, revenue: 3860, growth: 28.7 },
  { city: '广州', users: 41500, revenue: 2980, growth: 19.3 },
  { city: '杭州', users: 38900, revenue: 2750, growth: 32.1 },
  { city: '成都', users: 32400, revenue: 2280, growth: 26.8 },
  { city: '武汉', users: 28100, revenue: 1960, growth: 24.5 },
  { city: '西安', users: 24800, revenue: 1720, growth: 18.9 },
  { city: '南京', users: 22300, revenue: 1580, growth: 22.4 },
  { city: '重庆', users: 19800, revenue: 1390, growth: 17.6 },
];

export const MOCK_SEGMENT_DATA: Record<string, any>[] = [
  { name: '企业客户', value: 45, color: '#1e3a5f' },
  { name: '中小商家', value: 28, color: '#c9a962' },
  { name: '个人用户', value: 18, color: '#4a90a4' },
  { name: '合作伙伴', value: 9, color: '#7cb342' },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-2024-annual',
    name: '2024年度企业年报',
    description: '集团2024财年完整年度报告，包含财务数据、用户增长、市场扩张等核心内容',
    templateId: 'tpl-corporate-blue',
    status: 'draft',
    ownerId: 'u-001',
    createdAt: '2024-12-10T09:30:00Z',
    updatedAt: '2025-01-08T16:45:00Z',
    lastEditedBy: 'u-003',
  },
  {
    id: 'proj-2024-sustain',
    name: '2024 ESG可持续发展报告',
    description: '环境、社会与治理年度报告，展示企业社会责任成果',
    templateId: 'tpl-emerald-tech',
    status: 'published',
    ownerId: 'u-001',
    createdAt: '2024-11-20T14:00:00Z',
    updatedAt: '2024-12-28T10:20:00Z',
  },
  {
    id: 'proj-2024-brand',
    name: '2024品牌影响力白皮书',
    description: '品牌知名度、用户满意度、市场占有率分析报告',
    templateId: 'tpl-warm-elegance',
    status: 'draft',
    ownerId: 'u-001',
    createdAt: '2024-12-25T11:15:00Z',
    updatedAt: '2025-01-05T09:00:00Z',
  },
];

export const MOCK_DATA_SOURCES: DataSource[] = [
  {
    id: 'ds-revenue-001',
    projectId: 'proj-2024-annual',
    name: '季度营收与利润',
    fileName: 'quarterly_revenue_2024.xlsx',
    fields: [
      { key: 'quarter', label: '季度', type: 'string' },
      { key: 'revenue', label: '营收(万元)', type: 'currency' },
      { key: 'profit', label: '利润(万元)', type: 'currency' },
      { key: 'users', label: '用户数', type: 'number' },
    ],
    rows: MOCK_REVENUE_DATA,
    importedAt: '2024-12-11T10:00:00Z',
    importedBy: 'u-002',
    rowCount: 8,
    fileHash: 'abc123xyz',
  },
  {
    id: 'ds-city-001',
    projectId: 'proj-2024-annual',
    name: '城市覆盖数据',
    fileName: 'city_coverage_2024.csv',
    fields: [
      { key: 'city', label: '城市', type: 'string' },
      { key: 'users', label: '用户数', type: 'number' },
      { key: 'revenue', label: '营收(万元)', type: 'currency' },
      { key: 'growth', label: '增长率(%)', type: 'percentage' },
    ],
    rows: MOCK_CITY_DATA,
    importedAt: '2024-12-12T14:30:00Z',
    importedBy: 'u-002',
    rowCount: 10,
    fileHash: 'def456uvw',
  },
];

const createId = () => Math.random().toString(36).slice(2, 10);

export const buildDefaultSections = (projectId: string): PageSection[] => [
  {
    id: createId(),
    type: 'cover',
    title: '2024 年度企业报告',
    subtitle: '稳步前行，共绘未来',
    templateVariant: 1,
  },
  {
    id: createId(),
    type: 'toc',
    title: '目录',
  },
  {
    id: createId(),
    type: 'chart',
    title: '一、核心经营数据',
    subtitle: '年度营收与利润概况',
    charts: [
      {
        id: createId(),
        type: 'number',
        title: '年度总营收',
        dataSourceId: 'ds-revenue-001',
        width: 'quarter',
        styleConfig: {
          colorPalette: DEFAULT_PALETTES[0],
          showLegend: false,
          showGrid: false,
          showLabels: false,
          animationEnabled: true,
          strokeWidth: 2,
          barRadius: 4,
          fontFamily: 'Manrope',
        },
        numberValue: 69400,
        numberSuffix: ' 万元',
      },
      {
        id: createId(),
        type: 'number',
        title: '年度净利润',
        dataSourceId: 'ds-revenue-001',
        width: 'quarter',
        styleConfig: {
          colorPalette: DEFAULT_PALETTES[0],
          showLegend: false,
          showGrid: false,
          showLabels: false,
          animationEnabled: true,
          strokeWidth: 2,
          barRadius: 4,
          fontFamily: 'Manrope',
        },
        numberValue: 18780,
        numberSuffix: ' 万元',
      },
      {
        id: createId(),
        type: 'number',
        title: '累计用户数',
        dataSourceId: 'ds-revenue-001',
        width: 'quarter',
        styleConfig: {
          colorPalette: DEFAULT_PALETTES[0],
          showLegend: false,
          showGrid: false,
          showLabels: false,
          animationEnabled: true,
          strokeWidth: 2,
          barRadius: 4,
          fontFamily: 'Manrope',
        },
        numberValue: 418000,
        numberSuffix: ' 人',
      },
      {
        id: createId(),
        type: 'number',
        title: '覆盖城市数',
        dataSourceId: 'ds-city-001',
        width: 'quarter',
        styleConfig: {
          colorPalette: DEFAULT_PALETTES[0],
          showLegend: false,
          showGrid: false,
          showLabels: false,
          animationEnabled: true,
          strokeWidth: 2,
          barRadius: 4,
          fontFamily: 'Manrope',
        },
        numberValue: 58,
        numberSuffix: ' 座',
      },
      {
        id: createId(),
        type: 'line',
        title: '季度营收与利润趋势',
        dataSourceId: 'ds-revenue-001',
        xField: 'quarter',
        yFields: ['revenue', 'profit'],
        width: 'full',
        styleConfig: {
          colorPalette: DEFAULT_PALETTES[0],
          showLegend: true,
          showGrid: true,
          showLabels: true,
          animationEnabled: true,
          strokeWidth: 3,
          barRadius: 4,
          fontFamily: 'Manrope',
        },
      },
    ],
  },
  {
    id: createId(),
    type: 'chart',
    title: '二、业务结构分析',
    subtitle: '客户构成与业务分布',
    charts: [
      {
        id: createId(),
        type: 'bar',
        title: '主要城市用户分布 (Top 10)',
        dataSourceId: 'ds-city-001',
        xField: 'city',
        yFields: ['users'],
        width: 'half',
        styleConfig: {
          colorPalette: DEFAULT_PALETTES[0],
          showLegend: false,
          showGrid: true,
          showLabels: true,
          animationEnabled: true,
          strokeWidth: 2,
          barRadius: 6,
          fontFamily: 'Manrope',
        },
      },
      {
        id: createId(),
        type: 'pie',
        title: '客户群体构成',
        dataSourceId: 'ds-city-001',
        valueField: 'value',
        labelField: 'name',
        width: 'half',
        styleConfig: {
          colorPalette: DEFAULT_PALETTES[0],
          showLegend: true,
          showGrid: false,
          showLabels: true,
          animationEnabled: true,
          strokeWidth: 2,
          barRadius: 4,
          fontFamily: 'Manrope',
        },
      },
      {
        id: createId(),
        type: 'progress',
        title: '年度目标完成度',
        dataSourceId: 'ds-revenue-001',
        width: 'full',
        styleConfig: {
          colorPalette: DEFAULT_PALETTES[0],
          showLegend: false,
          showGrid: false,
          showLabels: true,
          animationEnabled: true,
          strokeWidth: 2,
          barRadius: 8,
          fontFamily: 'Manrope',
        },
        progressValue: 86.75,
        progressMax: 100,
      },
    ],
  },
  {
    id: createId(),
    type: 'content',
    title: '三、战略成果与展望',
    subtitle: '回顾2024，展望2025',
    content:
      '### 3.1 年度核心成就\n\n2024年是公司发展历程中具有里程碑意义的一年。在全体员工的共同努力下，我们取得了以下重要成就：\n\n- **营收规模再创新高**：全年总营收达到6.94亿元，同比增长52.3%\n- **用户基础持续扩大**：累计注册用户突破41.8万，同比增长97.2%\n- **市场覆盖稳步拓展**：业务覆盖城市增至58座，新进入12个重点城市\n- **盈利能力显著增强**：全年净利润达1.88亿元，净利率提升至27.1%\n\n### 3.2 战略重点方向\n\n公司将继续围绕以下三大战略方向推进业务发展：\n\n1. **技术创新驱动**：持续加大研发投入，保持技术领先优势\n2. **市场深耕细作**：巩固核心城市优势，加速下沉市场渗透\n3. **生态协同发展**：深化合作伙伴关系，构建共赢产业生态',
  },
  {
    id: createId(),
    type: 'text',
    title: '',
    content:
      '**结语**\n\n感谢每一位客户、合作伙伴和员工的信任与支持。站在新的起点，我们将继续秉持"创新、协作、共赢"的核心价值观，与您携手共创更加美好的未来。\n\n© 2024 企业名称 版权所有',
    templateVariant: 2,
  },
];

export const MOCK_ANALYTICS: AnalyticsSummary = {
  totalVisits: 12486,
  uniqueVisitors: 3872,
  avgDuration: 245,
  completionRate: 68.5,
  visitsByDay: [
    { date: '12-28', count: 842 },
    { date: '12-29', count: 1028 },
    { date: '12-30', count: 965 },
    { date: '12-31', count: 1584 },
    { date: '01-01', count: 2186 },
    { date: '01-02', count: 1842 },
    { date: '01-03', count: 1428 },
    { date: '01-04', count: 1056 },
    { date: '01-05', count: 924 },
    { date: '01-06', count: 631 },
  ],
  sectionAvgDurations: [
    { sectionId: 's1', sectionTitle: '封面', avgDuration: 8 },
    { sectionId: 's2', sectionTitle: '目录', avgDuration: 12 },
    { sectionId: 's3', sectionTitle: '核心经营数据', avgDuration: 58 },
    { sectionId: 's4', sectionTitle: '业务结构分析', avgDuration: 72 },
    { sectionId: 's5', sectionTitle: '战略成果与展望', avgDuration: 65 },
    { sectionId: 's6', sectionTitle: '结语', avgDuration: 18 },
  ],
  deviceBreakdown: [
    { device: '桌面端', count: 7246, percentage: 58.0 },
    { device: '移动端', count: 4420, percentage: 35.4 },
    { device: '平板', count: 820, percentage: 6.6 },
  ],
  countryBreakdown: [
    { country: '北京', count: 2856, percentage: 22.9 },
    { country: '上海', count: 2428, percentage: 19.4 },
    { country: '广东', count: 1965, percentage: 15.7 },
    { country: '浙江', count: 1248, percentage: 10.0 },
    { country: '江苏', count: 1086, percentage: 8.7 },
    { country: '其他', count: 2903, percentage: 23.3 },
  ],
};
